name = "life-cal-worker"
main = "src/index.ts"
compatibility_date = "2024-01-17"

[[routes]]
pattern = "life-cal.jes.bz"
custom_domain = true

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false

[dev]
port = 8787
